# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: work
        run: |
          cd loader
          npm ci
          npm run build
          npm run work
      - uses: actions/upload-artifact@v3
        with:
          name: vdt.db
          path: loader/vdt.db
