# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:

env:
  FTP_HOST: ${{vars.FTP_HOST}}
  FTP_USER: ${{vars.FTP_USER}}
  FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: app
      - name: work
        run: |
          cd app/loader
          npm ci
          npm run build
          npm run work
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: pages
      - name: copy db
        run: |
          ls
          cp app/public/data/vdt.db pages/data/vdt.db
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: pages
          commit_message: Update vdt.db
          branch: gh-pages
          file_pattern: 'data/vdt.db'
          status_options: '--untracked-files=no'
          add_options: '-u'
          push_options: '--force'