# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

env:
  FTP_HOST: ${{vars.FTP_HOST}}
  FTP_USER: ${{vars.FTP_USER}}
  FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: work
        run: |
          cp public/data/vdt.db loader
          cd loader
          npm ci
          npm run build
          npm run work
      - uses: actions/upload-artifact@v3
        with:
          name: vdt.db
          path: loader/vdt.db
