# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:

env:
  TZ: Europe/Moscow

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          path: app
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: pages
      - name: work
        run: |
          cp ${{github.workspace}}/pages/data/vdt.db ${{github.workspace}}/app/public/data/vdt.db
          cd app/loader
          npm i
          npm run build
          npm run work
          cp ${{github.workspace}}/app/public/data/vdt.db ${{github.workspace}}/pages/data/vdt.db
          cd ${{github.workspace}}/pages/data/
          zip vdt.zip vdt.db
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: pages
          commit_message: Update vdt.db
          branch: gh-pages
          file_pattern: 'data/vdt.*'
          push_options: '--force'